### ISSUE TITLE
Is there an example to create a Push subscription using Yammer REST API so that I get notified only when I am @mentioned in Yammer?

### ISSUE THREAD

**Issue by NehaJantre** [oscarrenalias/yammer-rest-api-client-node#18]
Is there an example to create a Push subscription using Yammer REST API so that I get notified only when I am @mentioned in Yammer? I am creating an application that generates toast notification in Windows Action Center when I am @mentioned in Yammer.

**Comment by oscarrenalias** [comment]
I don't have such an example, and I haven't worked on this library or with the Yammer API for some time so I wouldn't know how to do it, sorry!
